# LlamaEconomy Config
# pre-installed providers: yaml, mysql, mongodb
# Warning: when using MySQL you need to install DBDrivers.
Provider: "yaml"

DefaultMoney: 1000.0
MonetaryUnit: "$"

# --- MongoDB ---
MongoDB:
  Uri: "mysuperduperuri"
  Database: "llamaeconomy"

# --- MySQL ---
MySql:
  Host: "127.0.0.1"
  Port: "3306"
  User: "root"
  Password: "HAHA_XD_ROFL_123"
  Database: "llamaeconomy"

# Here you can edit the commands
Commands:
  Addmoney:
    Name: "addmoney"
    Description: "Add money to an player"
    Usage: "/addmoney <player> <amount>"
    Permission: "llamaeconomy.addmoney"
    Parameters: "player;amount" # Do not add or remove parameters!
    Aliases: ["givemoney", "baladd"]
  Money:
    Name: "money"
    Description: "Money Command"
    Usage: "/money <optional: player>"
    # no permission
    Parameters: "player"
    Aliases: ["mymoney", "getmoney", "bal", "balance"]
  Pay:
    Name: "pay"
    Description: "Pay money to a player"
    Usage: "/pay <player> <amount>"
    # no permission
    Parameters: "player;amount"
    Aliases: ["balpay"]
  Reducemoney:
    Name: "reducemoney"
    Description: "Reduce money of a player"
    Usage: "/reducemoney <player> <amount>"
    Permission: "llamaeconomy.reducemoney"
    Parameters: "player;amount"
    Aliases: ["takemoney", "baltake"]
  Setmoney:
    Name: "setmoney"
    Description: "Set money of an player"
    Usage: "/setmoney <player> <amount>"
    Permission: "llamaeconomy.setmoney"
    Parameters: "player;amount"
    Aliases: ["balset"]
  Topmoney:
    Name: "topmoney"
    Description: "View a list of the richest players"
    Usage: "/topmoney <optional: page>"
    # no permission
    Parameters: "page"
    Aliases: ["baltop"]
  Lecoreload:
    Name: "lecoreload"
    Description: "Reload language data of LlamaEconomy"
    Usage: "/lecoreload"
    Permission: "llamaeconomy.reload"
    # no parameters
    Aliases: ["lreload", "ecoreload"]